version: "2"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
  web:
    build: .
    command: sh -c "python3 manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers ${NUM_WORKERS:-1}"
    expose:
      - 8000
    volumes:
      - static:/app/backend/static
      - data:/app/backend/data
      - ${PWD}/.env:/app/.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static:/app/backend/static/
      - data:/app/backend/data/
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  db-data:
  data:
  static:
